### ISSUE TITLE
You cant neste multiple Inputs

### ISSUE THREAD

**Issue by d-pruessmeier** [VORPCORE/vorp_inputs-lua#9]
if i try to neste inputs like this for example:
-- CODE IN ATTACHED FILE
----------------------------------------------

The Second Inner Input will not pop up. No errors givin.

[nestedInputs.txt](https://github.com/VORPCORE/vorp_inputs-lua/files/12719939/nestedInputs.txt)

**Comment by outsider31000** [comment]
This isn't an issue
open one at the time instead one on top of the other.
